#!/usr/bin/env python3
"""Generate the mechanically checked developer current-state inventory."""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "dev" / "current-state-inventory.md"
AUDIT_GLOB = "*audit*.md"
HISTORICAL_MARKER = "**Historical snapshot — not contract authority.**"

TRANSPORTS = (
    (
        "Matrix",
        "matrix",
        "src/medre/adapters/matrix/event_shape.py",
        "MATRIX_NATIVE_SCHEMA_VERSION",
    ),
    (
        "Meshtastic",
        "meshtastic",
        "src/medre/adapters/meshtastic/event_shape.py",
        "MESHTASTIC_NATIVE_SCHEMA_VERSION",
    ),
    (
        "MeshCore",
        "meshcore",
        "src/medre/adapters/meshcore/event_shape.py",
        "MESHCORE_NATIVE_SCHEMA_VERSION",
    ),
    (
        "LXMF",
        "lxmf",
        "src/medre/adapters/lxmf/event_shape.py",
        "LXMF_NATIVE_SCHEMA_VERSION",
    ),
)


def _integer_constant(path: str, name: str) -> int:
    source = (ROOT / path).read_text(encoding="utf-8")
    tree = ast.parse(source, filename=path)
    for node in tree.body:
        target: ast.expr | None = None
        value: ast.expr | None = None
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            target = node.target
            value = node.value
        if (
            isinstance(target, ast.Name)
            and target.id == name
            and isinstance(value, ast.Constant)
            and isinstance(value.value, int)
            and not isinstance(value.value, bool)
        ):
            return value.value
    raise RuntimeError(f"{path}: missing integer constant {name}")


def _current_event_schema_version() -> int:
    return _integer_constant(
        "src/medre/core/events/schema.py", "CURRENT_SCHEMA_VERSION"
    )


def _audit_files() -> list[Path]:
    return sorted((ROOT / "docs" / "dev").glob(AUDIT_GLOB), key=lambda p: p.name)


def _native_metadata_table() -> str:
    headers = (
        "Transport",
        "Persisted namespace",
        "Version",
        "Source authority",
        "Machine schema",
    )
    rows: list[tuple[str, ...]] = []
    for label, namespace, source, constant in TRANSPORTS:
        version = _integer_constant(source, constant)
        schema = f"docs/schemas/{namespace}-native-metadata.schema.json"
        rows.append(
            (
                label,
                f"`native.{namespace}`",
                f"`{version}`",
                f"`{source}`",
                f"`{schema}`",
            )
        )

    widths = [
        max(len(header), *(len(row[index]) for row in rows))
        for index, header in enumerate(headers)
    ]

    def format_row(row: tuple[str, ...]) -> str:
        cells = [
            (f"{value:>{widths[index]}}" if index == 2 else f"{value:<{widths[index]}}")
            for index, value in enumerate(row)
        ]
        return "| " + " | ".join(cells) + " |"

    separators = tuple(
        "-" * (width - 1) + ":" if index == 2 else "-" * width
        for index, width in enumerate(widths)
    )
    return "\n".join(
        (
            format_row(headers),
            format_row(separators),
            *(format_row(row) for row in rows),
        )
    )


def render() -> str:
    native_metadata_table = _native_metadata_table()
    audits = _audit_files()
    audit_rows = "\n".join(f"- `{path.name}`" for path in audits)
    event_version = _current_event_schema_version()

    return f"""# Current State Inventory

> **Generated current-state reference.** Do not edit this file by hand. Run
> `python scripts/generate-current-state-inventory.py` after changing a listed
> authority. Normative behavior remains defined by `docs/spec/`, machine schemas,
> and source contracts.

## Contract Authorities

1. `docs/spec/` defines normative semantics.
2. `docs/schemas/` defines machine-readable serialized contracts.
3. Source models/builders implement those contracts.
4. Tests verify source/schema/example agreement.
5. Developer audit documents are historical evidence only.

## Canonical Event Envelope

- Current envelope schema version: `{event_version}`.
- The envelope is closed and versioned; unknown top-level fields are not an
  extension mechanism and may be ignored during decode.
- Extensible producer data belongs in `payload`, `metadata.custom`, or a
  versioned transport-native namespace.
- No canonical-event migration registry is present.

## Built-In Native Metadata

{native_metadata_table}

Cross-product MMRelay wire interoperability is isolated under
`native.interop.mmrelay`; it is not an alternate MEDRE native-event shape.

## Compatibility Policy

`docs/spec/compatibility-boundaries.md` classifies every supported compatibility
seam. External wire/SDK differences and bounded current-runtime degradation may
be retained; abandoned MEDRE development shapes are rejected rather than read
through compatibility branches.

## Route Configuration

`channel_room_map` has one supported entry representation: a structured mapping
with required `room` plus optional `source_origin_label` and
`dest_origin_label`. Bare room-ID values are rejected.

## Runtime Entry Points

- Live adapter ingress requires durable storage admission.
- Tests and explicit internal callers use `PipelineRunner.handle_ingress` when
  bypassing durable admission intentionally.
- Replay renderers implement `render_replay_event`; there is no alternate
  replay-render hook.

## Historical Audit Snapshots

There are {len(audits)} historical audit snapshot files. Every file listed below
must carry the historical-snapshot marker and must not be treated as current
contract authority:

{audit_rows}
"""


def _schema_version(schema_path: Path, namespace: str) -> int:
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    definitions = schema.get("$defs", {})
    if not isinstance(definitions, dict):
        raise RuntimeError(f"{schema_path}: missing $defs")
    candidates = [
        value
        for value in definitions.values()
        if isinstance(value, dict)
        and isinstance(value.get("properties"), dict)
        and "schema_version" in value["properties"]
    ]
    if len(candidates) != 1:
        raise RuntimeError(
            f"{schema_path}: expected one versioned {namespace} definition"
        )
    version_property = candidates[0]["properties"]["schema_version"]
    version = (
        version_property.get("const") if isinstance(version_property, dict) else None
    )
    if isinstance(version, bool) or not isinstance(version, int):
        raise RuntimeError(f"{schema_path}: schema_version const must be an integer")
    return version


def _example_version(example_path: Path, namespace: str) -> int:
    example = json.loads(example_path.read_text(encoding="utf-8"))
    native = example.get(namespace) if isinstance(example, dict) else None
    if not isinstance(native, dict):
        raise RuntimeError(f"{example_path}: missing {namespace!r} namespace")
    version = native.get("schema_version")
    if isinstance(version, bool) or not isinstance(version, int):
        raise RuntimeError(f"{example_path}: schema_version must be an integer")
    return version


def _channel_room_map_is_structured_only() -> bool:
    schema = json.loads(
        (ROOT / "docs" / "schemas" / "routing-config.schema.json").read_text(
            encoding="utf-8"
        )
    )
    entry = schema.get("$defs", {}).get("ChannelRoomMapEntry")
    if not isinstance(entry, dict):
        return False
    if entry.get("type") != "object" or entry.get("required") != ["room"]:
        return False
    if entry.get("additionalProperties") is not False:
        return False

    occurrences: list[dict[str, object]] = []

    def walk(value: object) -> None:
        if isinstance(value, dict):
            channel_map = value.get("channel_room_map")
            if isinstance(channel_map, dict):
                occurrences.append(channel_map)
            for child in value.values():
                walk(child)
        elif isinstance(value, list):
            for child in value:
                walk(child)

    walk(schema)
    if not occurrences:
        return False
    expected_ref = "#/$defs/ChannelRoomMapEntry"
    for occurrence in occurrences:
        variants = occurrence.get("oneOf")
        if not isinstance(variants, list):
            return False
        mapping_variants = [
            variant
            for variant in variants
            if isinstance(variant, dict) and variant.get("type") == "object"
        ]
        if len(mapping_variants) != 1:
            return False
        if mapping_variants[0].get("additionalProperties") != {"$ref": expected_ref}:
            return False
        if any(
            isinstance(variant, dict) and variant.get("type") == "string"
            for variant in variants
        ):
            return False
    return True


def check() -> int:
    expected = render()
    actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if actual != expected:
        print(f"{OUTPUT.relative_to(ROOT)} is out of date")
        return 1
    missing = []
    for path in _audit_files():
        if HISTORICAL_MARKER not in path.read_text(encoding="utf-8"):
            missing.append(path.name)
    if missing:
        print("audit files missing historical marker: " + ", ".join(missing))
        return 1
    if "MIGRATION_REGISTRY" in (
        ROOT / "src" / "medre" / "core" / "events" / "schema.py"
    ).read_text(encoding="utf-8"):
        print("canonical event migration registry unexpectedly present")
        return 1
    for _label, namespace, source, constant in TRANSPORTS:
        source_version = _integer_constant(source, constant)
        schema_path = (
            ROOT / "docs" / "schemas" / f"{namespace}-native-metadata.schema.json"
        )
        example_path = (
            ROOT
            / "docs"
            / "schemas"
            / "examples"
            / f"{namespace}-native-metadata-example.json"
        )
        schema_version = _schema_version(schema_path, namespace)
        example_version = _example_version(example_path, namespace)
        if source_version != schema_version or source_version != example_version:
            print(
                f"{namespace}: schema-version drift "
                f"source={source_version} schema={schema_version} example={example_version}"
            )
            return 1
    if not _channel_room_map_is_structured_only():
        print(
            "routing schema does not enforce structured-only channel_room_map entries"
        )
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    OUTPUT.write_text(render(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
